#RuleBook Travis CI config for maven deploy
language: java
env:
  global:
    #OSSRH_USERNAME
    - secure: "QtZ0h7bfVQ7Juw3SdaXk77AT5bQUlI3YhBZnOAOhjK6IVlPcYGMUY0J+CK2ogSoCkjoGFK+2PcBYvBalscQ0U3atY/MGvbmLA/uj8OjiFHoW2pdTWPIaiLOucOr6t2QVZoC4eSghpyTUVtdbVLt4h+rN3YRyVqxBC/wdN17lq+xgf2vRMk/4+DQxQrEu8UyvwJB1fPNJcU2goZRPwvxFp+PXQsTGfMWdNpl121lZrUnSk0ua+ZR4mFzWaNNFaQz7rSPhH/kpjhjRfTnH+vf9wYUA6iFxqx6YL0+pL64PFB+nYZnxL2gYYMU2uqnpKaWJ+6Hv0Q1OXOJ88LA6AtE6rlPZhBoglbk744Q8XK84ewwBt3NCTsZ3sM0sez9iWR8lkwmkiPlYxAosFRfVxQ8YYa0uoT1/GDwOBfsd4x3tsxQRFMV6quKAnaxM02tJOC4OxCw9ul/Gd8SJBumxPKLJCNA9Dbc1d1TVhgltyMMEzpz2lBgJwyV1i2xM/JAgoZd/dLP2JjLB397HnpIZYqO8prXKmX0Y+ba73uan6qpkobIJaV7tuDJznTjcrzrGo2akFmCeEcCSe+rKYSx7Y8buYQzDR4AeL4Te/FbP6CII2QK6MdmYvcTyMKnYL9viU+SkkM76EX1mzQrmviMm9Ze/Z6xWGdzFG39Ns0zMMbw1SyY="
    #OSSRH_PASSWORD
    - secure: "UZ5SRC7sZlkP/rBDzThtcYICpGCeaOzVAC0LzazYd1LgyF29EOiSTLhHjhXOr+E03konKAdKm3nVFld4rl5KJNk/egBlelmDQ6MoLLhGiAujukXPVi1rZ1f/ondpFbzysZub2JM6VkNqJRLKOWQbgZRLcmU2XFJVTQhR0G4O7E917RWF83JAXcTW4US5Dwiv3e90ne83wbA0d3CADrCU9FVi3Qqxv8Pu86x3rZFkcS9tvkhKUb0fJfEUwZaf5zs8o7FURrT7KUJ/cCItECEyBhLlX1C2Dm5s8hyhMsvN11LLPZu5uvqSKLCqY5AAsBxK1C0n5qEbT/ZkAPFQEMGQmqDsxayKqrvQAPJSdDx3tcTyd6zlrDmHuUGQNIDb/oQ0bIYR5qWf+ymRyCHGGhaCvoexJvKqQ9wzJIhlzQwAmWn+rwrwNCytP4C9krFlqpIpPqzXLk9pCIpbMMh302567UAmsfhO5/QQWQhaHnKdZKa6qmmG0QeIEhcAbxPZUOOHWHGjJMaU1O29GFioNgMTRLXAusvpx5bRowyHqtyicDapXACcyeqjr3vSXYq87DTe3rJTRcM6FnIa1eFg8KjyOxZVsdDg/RwXauEKBB1EH5SMmB5shwgegvvP6Khr2r5BLCE1i7CGqEUCOvQ6/Az/fRetkVsz+qNqTpffxL4zWpA="
    #SIGN_KEY_ID
    - secure: "k47AuMintqVBMRiWDHOUVwYCS5JdYx8j4Xoenf3PhUMBigmHHOgD/VSO9tjVEpmkWqWAZldNmDlmKwV0bWwMlnxihBus7/ajpX5UaX6cmD3d164Dg8E7UGUekRsRrZHvhERuAGedaPG5WtxtTlaejy3+gDasS85AIPN70MS/co62T1y7PpGcSHennZNpBlt/V5W7eA8dBiQXpJlFFPcICskm1qdE7uQnvdTvR/qN8vnkkPzP9SED2zlP6Ae/e/Xhf4xGTjd1Z5/qGiF4F4qePuiIGWKvqIo55Yph6o4XRTOmJUjUcBJqzBlgS3hqjG9NOR+2vb6eva1MAXlTbuD7sZgN12ujyHsbvDj/Z/5aNI5g4FpHovaz3xIHn4fcOZE+aAwNd3LwGQeuX/fFBfj+hZzljLv7eeRaW9X4Q7CP0l/aB00jcWt+U7qvpf/mTNoucBD7XFGlHjGnj+VPPEHxOlyRPUTzInvlMIWqqNcAGNQmWPM7J1T+FLQf6SsgorY3jG7j9mieB05p3X/DD9daXSjwbhKukFTtRBTIHCE5mUoYqW34W1nm7+Y8UP/g1U8d0eA3Pd9iuY5ApmOEsh0zK2EbKGJtqvdGWg2rV0vwIhqUjJ5mdPjphizxsxDgiENfoQ6kdpBcZYC+CwOuI/W3VKKyQ8ljDNkdT7+GzL2lVag="
    #KEY_PASSPHRASE
    - secure: "QS/Gb5L4Ymk8PC7WpSOApU7txjgPud/Rkgp55fw91xeiGiHiUQbXK9CJdT/1FW8YwVbqlfTZV/AT3Rtzm3Vv6SWkH8PleWD6hc4vpIx0iLZVtg87m+REzwL2dcit0iw5HXpF2TpbBRutWg9awyAc2JRCqLX/mWfk4ucmZ3QSWxWu7grG2VHtanW2geh5VLJfaHGLMsJKgeG6VPf+F8cQYfj2fkRowkbZCzIqmTB+C0XY6s5Et0GcBQGfkwh8jM7e9BRrKEq9Y99gsW6UT85gfzIlrWUtUijqSWCVQtb4WVQXJP5DHULNHF5C63/Q3por+e+2UCXldLDgVetLJnnyrEcD1dSyXgck2bEBCs7zu/EZzAjZve8xTfsReuyy68Ygd4nsIONm0wTyET4xP182fuia3xaN7W0ukONPWXXHFhgLm5p5rHFyN44dE1qx34+5UbFqdfpvSNJGN4ugQsoAucmGjsGXCgr/S0qv+BBrVXkAcuQaCEhCQI1nW2JbEpPYhWQcJb8I161h8Wio5WFU81LFmAzHVIP4XNEVmf4wyly/RykIMREAN53hyW1Mzd3lhY+/O5exdTwqcaYUvnOx3RVi3tH4YWsO5ZnkKvZC7xHGaC+lp2+vurxW6S64OvpeagP/n4J+8iYBicl89kFEqWjpWbL7GqdNSecGdCVpq0Y="

sudo: false
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.gradle
jdk:
  - oraclejdk8
script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
  - ./gradlew coveralls
after_success:
  - ./travis/deploy.sh
