# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: pr build

on:
  pull_request:
    branches: [ develop, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          CI_NAME: "GitHub Actions"
          CI_BUILD_NUMBER: ${{ env.GITHUB_RUN_ID }}
          CI_PULL_REQUEST: ${{ github.event.pull_request.number }}
          CI_BUILD_URL: "https://github.com/deliveredtechnologies/rulebook/pull/${{ github.event.pull_request.number }}/checks?check_run_id=${{ env.GITHUB_RUN_ID }}"
          CI_BRANCH: ${{ github.event.pull_request.head.ref }}



        run: |
          CI_PULL_REQUEST=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "***** CI_NAME: ${CI_NAME} *****"
          echo "***** CI_BUILD_NUMBER: ${CI_BUILD_NUMBER} *****"
          echo "***** ${CI_BUILD_URL} *****"
          echo "***** Updating Coverage for PR ${CI_PULL_REQUEST} on BRANCH ${CI_BRANCH} *****"
          ./gradlew check jacocoRootReport copySource coveralls
